abstract: abstract base class for Sledge's view
author: Tokuhiro Matsuno  C<< <tokuhiro __at__ mobilefactory.jp> >>
build_requires: 
  Class::Trigger: 0
  Test::Base: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Sledge-View
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  UNIVERSAL::require: 0
version: 0.01
